name: lcwassist
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.3
  barcode_scan:
  outline_material_icons: ^0.1.0
  charts_flutter: ^0.4.0
  sqflite : any
  http: 
  localstorage: ^1.0.0
  speech_recognition: ^0.3.0
  simple_permissions: ^0.1.9
  # flutter_secure_storage: ^3.1.2
  # path_provider: ^0.4.1
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  json_annotation:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imglogolcwassist.png
    - imglogo.png
    - logoLCWaikikiBlue.png
    - assets/defaultMalePP.png
    - assets/barcode_40.png
    - assets/barcode_gir_40.png
    - assets/barcode_tara_80.png
    - assets/search_40.png
    - assets/loginBackground.png
    - assets/outline_touch_app_white_18dp.png
    - assets/chart_1.png
    - assets/chart_2.png
    - assets/chart_3.png
    - assets/chart_4.png
    - assets/store_image.png
    - assets/chart_5.png
    - assets/chart_6.png
    - assets/chart_7.png
    - assets/data/languages.json
    - assets/splas.png
    - assets/drawerSplash.png
    - assets/drawerSplash.jpg
    - assets/homepageFeedback_128.png
    - assets/homepageFeedback_256.png
    - assets/homepageFeedback_512.png
    - assets/homepageFeedback_32.png
    - assets/homepageFeedback_48.png
    - assets/star_40.png
    - assets/right_oval_40.png
    - assets/message_balon_40.png
    - assets/subHeader.png
    - assets/login.png
    - assets/login.jpg
    - assets/deneme_rapor.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts: 
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Light.ttf
          weight: 700        
    - family: UbuntuMono
      fonts:
        - asset: fonts/UbuntuMono-Regular.ttf
        - asset: fonts/UbuntuMono-Bold.ttf
          weight: 700
          
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
